### ISSUE TITLE
Replace git dependency "preferences": "git+https://github.com/caffeinalab/preferences.git", with NPM https://www.npmjs.com/package/preferences?activeTab=dependencies

### ISSUE THREAD

**Issue by stefanseeger** [bsorrentino/confluence-site-publisher#14]
Hello,
would you please replace the git dependency of preferences with an actual one published to npm https://www.npmjs.com/package/preferences?activeTab=dependencies 

Thank you and keep up the good work.
Stefan

**Comment by bsorrentino** [comment]
fixed in release `3.2.1`
