### ISSUE TITLE
Works for Confluence Cloud/Server?

### ISSUE THREAD

**Issue by javimsevilla** [bsorrentino/confluence-site-publisher#17]
Hi 👋🏻,

First of all, good work doing this CLI! 👍🏻 

I would like to know if it works with Confluence Cloud, Confluence Server or both.

Thank you very much 😃

**Comment by bsorrentino** [comment]
Hi @javimsevilla  thanks for interest 

I've tested it on both, please try it and let me know any feedback or issue
